version: '3.9'

services:
  app:
    build:
      context: ../
      dockerfile: .docker/Dockerfile
      args:
        APP_ENV: ${APP_ENV}
    container_name: gb_tgbot-app
    restart: on-failure
    working_dir: /app  # Явно указываем рабочий   
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ../:/app
    networks:
      - bot_network

  db:
    image: mysql:8.0
    container_name: gb_tgbot-db
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - .docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - .docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - bot_network

  adminer:
    image: adminer
    container_name: gb_tgbot-adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - bot_network

  redis:
    image: redis:alpine
    container_name: gb_tgbot-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - bot_network

volumes:
  db_data:

networks:
  bot_network:
    driver: bridge
